server:
  port: 8080

spring:
  application:
    name: trendpulse-core-backend

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 5
          multiplier: 2.0

logging:
  level:
    com.trendpulse: INFO
    org.springframework.amqp: WARN
